#!/usr/bin/env python3
"""Render the SDLC definition as a Mermaid diagram — the pipeline
section of docs/architecture.md is GENERATED from orchestrator/
definition.py by this script (test_definition asserts the doc matches),
so the picture cannot drift from the graph the engine actually runs.

    python scripts/render_pipeline.py            # print the block
    python scripts/render_pipeline.py --write    # rewrite the doc section
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from sdlc.definition import (  # noqa: E402
    GATE, PER_ITEM_EDGES, REASONING, SDLC, START, TERMINALS, PipelineShape,
    per_item_edges)

DOC = ROOT / "docs" / "architecture.md"
BEGIN = "<!-- pipeline:begin (generated by scripts/render_pipeline.py) -->"
END = "<!-- pipeline:end -->"

# Display names; `*` marks a reasoning agent, `⛩` the human gate.
_LABEL_OVERRIDES = {
    "coder_fix": "coder* (fix)",
    "coder_flag_fix": "coder* (flag fix)",
    "preprod_ci": "preprod CI",
    "approval_gate": "human gate ⛩",
    "code_reviewer": "reviewer*",
}


def _label(name: str) -> str:
    if name in _LABEL_OVERRIDES:
        return _LABEL_OVERRIDES[name]
    step = next((s for s in SDLC.all_steps() if s.name == name), None)
    text = name.replace("_", " ")
    if step and step.kind == REASONING:
        text += "*"
    if step and step.kind == GATE:
        text += " ⛩"
    return text


def _node(name: str) -> str:
    nid = name.replace("-", "_")
    if name in TERMINALS:
        return f"{nid}((\"{name}\"))"          # terminal: circle
    return f"{nid}[\"{_label(name)}\"]"


def render(edges=PER_ITEM_EDGES) -> str:
    lines = ["```mermaid", "flowchart LR"]
    # planning: a straight chain into the per-item START
    prev = "backlog[(backlog)]"
    lines.append(f"    {prev}")
    for step in SDLC.planning:
        lines.append(f"    {prev.split('[')[0]} --> {_node(step.name)}")
        prev = _node(step.name)
    lines.append(f"    {prev.split('[')[0]} --> coder")
    # per-item graph, exactly as PER_ITEM_EDGES
    declared: set[str] = set()
    for src, dst, route in edges:
        if src == START:
            continue
        for n in (src, dst):
            if n not in declared:
                lines.append(f"    {_node(n)}")
                declared.add(n)
        arrow = f"-->|{route.value}|" if route else "-->"
        lines.append(f"    {src} {arrow} {dst}")
    # release: queued feeds the release phase
    prev = "queued"
    for step in SDLC.release:
        lines.append(f"    {_node(step.name)}")
        lines.append(f"    {prev} --> {step.name}")
        prev = step.name
    lines.append(f"    {prev} -->|merge + traffic shift| prod[\"Cloud Run\"]")
    lines.append("```")
    lines.append("")
    lines.append("`*` = reasoning agent; `⛩` = the human decides (on the PR); "
                 "double circles are terminal store statuses. Everything "
                 "else is deterministic.")
    return "\n".join(lines)


def block() -> str:
    return f"{BEGIN}\n{render()}\n{END}"


def write() -> None:
    text = DOC.read_text()
    pattern = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.S)
    if not pattern.search(text):
        raise SystemExit(f"{DOC}: markers not found — add {BEGIN} … {END} once")
    DOC.write_text(pattern.sub(lambda _: block(), text))
    print(f"wrote {DOC.relative_to(ROOT)}")


if __name__ == "__main__":
    if "--no-human-gate" in sys.argv:      # preview a project shape
        print(render(per_item_edges(PipelineShape(human_gate=False))))
    else:
        write() if "--write" in sys.argv else print(block())
